const buildMap = (pairs: [string, string][]) => {
  const map: Record<string, string> = {};
  pairs.forEach(([k, v]) => { map[k] = v; });
  return map;
};

export const ACADEMIC_QTY_MAP = buildMap([
  ["Hospital Bed Space", "250 minimum"],
  ["Embalmed Bodies", "1 cadaver per set of 6 students"], ["Anatomage Table", "1"], ["Equipment Trolleys", "3"], ["Electric Embalming Machine", "1"], ["Bone Cutting Equipment - Electric Saw/Drill", "2"], ["Articulated and Unarticulated Skeletons", "5"], ["X-ray Viewing Boxes", "4"], ["Air-conditioners and Air Extractors", "4"], ["Models", "5"], ["Slide for Sections", "Many"], ["Slide Projectors", "3"], ["Toilet Facilities:", "Gender sensitive"], ["Changing Room", "2"], ["Shower Room", "1"],
  ["Microtome", "2"], ["Rotary/Sledge Microtome Knives", "3"], ["Light Microscopes Microtome", "1 per 2 students"], ["Vacuum Pump Dissecting Microtome", "3"], ["Cryostat with Microtome", "3"], ["Teaching Microscope", "3"], ["Electron Microscope", "1 per 2 students"], ["Slides", "Many"], ["Centrifuge", "6"], ["Ultracentrifuge", "2"], ["Electronic Balances", "2"], ["Heating Block", "8"], ["Vacuum Pumps", "2"], ["Spectrophotometer", "1 per 10 students"], ["PH. Metres", "1 per 5 students"], ["Thermostatic Water Bath", "1"], ["Burner", "3 per bench"], ["Test Tube (varying sizes)", "Many"], ["Distiller", "3"],
  ["Spirometer", "1 per 5 students"], ["Vitalograph", "1 per 5 students"], ["Polygraph", "1"], ["Peak Flow Metre", "1 per 5 students"], ["Gas Metre", "2"], ["ECG Machine", "4"], ["Spectrophotometers", "1 per 5 students"], ["Physiograph Recorder Transducers", "1 per 5 students"], ["Oscilloscopes", "4"], ["Centrifuges", "6"], ["Blood Gas Callipers", "2"], ["Audiometer", "2"], ["Water Baths", "2"], ["Electronic Weighing Balance Scale", "2"], ["Flame Photometer", "4"], ["Microcentrifuge", "2"], ["Water Distiller", "5"], ["Bicycle Ergometer", "3"], ["Stethoscopes/Sphygmomanometres", "12"], ["Snelle's Chart", "5"],
  ["Multi Gym", "2 minimum"], ["Treadmill", "5"], ["Elliptical Bicycle Ergometer", "2"], ["Recumbent Bicycle Ergometer", "2"], ["Hand Exerciser", "5"], ["Shoulder Wheel", "2"], ["Shoulder Ladder", "2"], ["Quadriceps Drill/Bench", "1"], ["Traction Units (cervical/lumbar)", "1 each"], ["Medicine Ball (5 varying weights)", "1 each"], ["Exercise Ball", "5"], ["Reciprocal Pulley", "5"], ["Steppers", "10"], ["Wooden Staircase (firm/shakeable)", "2"], ["Wobble Board", "5"], ["Parallel Bar", "2"], ["Standing Mirror", "4"], ["Exercise Mat", "5"], ["Sitting Box", "5"], ["Standing Box", "4"], ["TheraBands:", "10 each of different colours"], ["Handgrip Exerciser", "5"], ["Dumbbells (1, 2, 3, 4, 5kgs)", "5 each"], ["Sand Bags (1, 2, 3, 4, 5kgs)", "5 each"], ["Walking Frames", "10"], ["Suspension Therapy Unit", "1"], ["Crutches (Elbow and Axillary)", "10"], ["Wheel Chairs", "5"], ["Weighing Scale", "5"], ["Stadiometer", "5"], ["Pulse Oximeter", "5"], ["Tape Measure", "10"], ["Sphygmomanometer", "10"], ["Stethoscope", "10"], ["Walking Sticks, Quadruped & Tripod", "10"], ["Precision Box", "3"], ["Exercise Couch", "5"], ["Finger Ladder", "2"],
  ["TENS Machine", "4"], ["EMS Machine", "3"], ["IRR Luminous", "4"], ["IRR Non-luminous", "2"], ["Shortwave Diathermy", "2"], ["Wax Bath", "4"], ["UVR", "5"], ["IF Therapy", "3"], ["Shock Wave", "2"], ["Micro Wave", "2"], ["Ice Making Machine", "3"], ["Therapeutic Ultrasound", "3"], ["Laser or Light Therapy", "3"], ["Hydrocollator Unit", "2"], ["Pneumatic Machine", "2"], ["Standard Hydrotherapy Pool", "1"], ["Aquatic Ergometer", "1"], ["Aquatic Treadmill", "1"], ["Life Jacket", "4"],
  ["High Impedance Mannequin", "One high impedance mannequin"], ["Mannequins and Beds in the Laboratory:", "10 manual mannequins and 10 beds"], ["Manual Mannequins", "10"], ["Beds", "10"], ["Goniometers", "4"], ["Sphygmomanometer / Stethoscope", "4"], ["Spirometers", "4"], ["Peak Flow Meters", "4"], ["Skin Fold Callipers", "4"], ["One Stop Watch", "4"], ["Hand Grip Dynamometer /Digital Dynamo", "5"], ["Scale Weight (wheelchair accessible)", "3"], ["Pain Rating Scale", "4"], ["Sensory Processing Test Equipment", "2"], ["Heart Rate Monitor", "5"], ["Cognitive Test Equipment", "5"], ["EMG", "1"], ["Body Mass Index Calculator", "5"], ["Reflex Hammer", "5"], ["Tongue Depressor (Pack)", "Packs"], ["Tuning Fork (128Hz)", "5"], ["Two Test Tubes", "5"], ["Familiar Objects (e.g. paper clip, coin, marble)", "4"], ["Pen Light", "5"], ["Thermometer", "5"], ["Cotton Ball or Cotton Tipped Swab (Pack)", "Packs"], ["Periniometer", "4"],
  ["Gait Trainers", "3"], ["Precision Boxes", "3"], ["Precision Toys", "10"], ["Giant Mirrors", "Wall to wall"], ["Prone Standers", "4"], ["Standing Frames", "5"], ["treatment Plinths", "4"], ["Therapy Balls/Medicine Balls", "5"], ["Posterior Walkers", "4"], ["Wedges and Rolls", "5 each"], ["Frenkel Mats", "2"], ["Paediatric Treadmill", "2"], ["Resistance Bands", "10"], ["Paediatric Crutches", "5"], ["Paediatric Tilt Bed", "2"], ["Supportive Garment", "3"], ["Stabilization Belts", "3"], ["Everyday Objects for ADL", "10"], ["Adapted Eating and Drinking Products", "5"], ["Suctioning Machine", "2"], ["Tilt Bed", "2"], ["TheraBand - Resistance Band (Yellow, Green, Blue, Red)", "10 each"], ["Neuro-com Balance Master", "3"], ["Wheelchair - Motorised", "2"], ["Walking Sticks", "3"], ["3 by 4 Wheeled Walker", "3"], ["Gait Belts", "3"], ["Wall Bar", "2"], ["Standing Infra-red Lamp (luminous/non-luminous)", "3"], ["Metronome", "5"], ["Spit Basin", "8"], ["Flashlight", "10"], ["Cognitive Test Equipment (PD & dementia)", "10"], ["Transfer Boards/Slide Sheet", "8"], ["Pillows", "10"], ["Foam Rollers/Wedges", "10 each"], ["Splinting Kit (static/dynamic)", "5 each"], ["Orthoses Kit", "5"], ["Casting Kit", "5"], ["Rollator", "5"], ["Equipment for Sport and Recreational Activities", "10"], ["Upper Limb Supports", "5"], ["Upper Limb Workstation", "5"], ["Arm Activity Kit", "5"], ["Cycle Ergometer (arm or leg)", "4"], ["Stools/Small Benches of varying Height", "5 each"], ["Ramps (temporary/mobile)", "5 each"], ["Training Stairs", "2"], ["Steps (stackable)", "2"], ["Balance Board/Cushion", "3"], ["Resistive Exercise Putty", "5"], ["Exercise or Gym Balls", "5"], ["TENS Supply Kit", "4"], ["Treatment Tables", "5"], ["(Functional) Electrical Stimulation Kit", "2"], ["Assistant Support Belt", "3"], ["Weighing Scale & Measuring Tape", "2"], ["Cycle Ergometer (Arm & Leg)", "2"], ["Timer", "5"],
  ["Lumber & Cervical Traction Bed", "1"], ["Treadmill Machine", "3"], ["Precision Board", "4"], ["Dumbbells:", "One pair each (12)"], ["Tera Bands", "10"], ["Hand Exerciser Balls", "4"], ["Wax Bath Machine", "2"], ["Short Wave Diathermy Machine", "1"], ["Interferential Current Machine", "2"], ["Transcutaneous Electrical Muscle Stimulator", "3"], ["Electrical Muscle Stimulators", "3"], ["Ultraviolent Machine", "1"], ["X-ray Viewing Machine", "2"], ["Therapeutic Ultra Sound Machine", "3"], ["Walking Frames/W", "5"], ["Rollators", "5"], ["Crutches, Axillary/Elbow", "5"], ["Canes/Sticks/Tetrapod", "5"], ["Hot and Cold Packs", "5"], ["Vaginal Cones (diff sizes)", "5 each"], ["Small and Large Exercise Balls", "5 each"], ["Dumbbells of different sizes", "5"], ["Screen", "5"], ["Portable TENS", "4"], ["Pedometer", "4"], ["Ultrasound Imaging", "2"], ["Vaginal and anal Sensors", "5 Packs"], ["Vaginal Weight", "3 each"], ["Pelvic Models (male and female)", "3 each"], ["Tubi Grip", "3"], ["Pelvic Belts / SPD belts", "4"], ["Peristeen Irrigation system", "2 each"], ["Aquaflush compact system", "2 each"], ["Qufora irrigation", "2 each"], ["Navina Irrigation system", "2 each"], ["Pessaries - require trained therapist for fitting", "2"], ["Contiform", "2 each"], ["Contrelke", "2 each"], ["Efemia", "2 each"], ["Revive", "2 each"], ["Cryotherapy in the form of ice fingers (made using examination gloves)", "4"], ["Foam Wedge", "5"], ["Biofeedback Machine", "2"], ["Vibrators (Patient acquired-personalized)", "2"], ["Pelvic Wand", "4"], ["Kegel Balls", "5"], ["Surface Electrodes", "10"], ["Lubricating Gel", "5 packs"], ["Vaginal balls for Kegel exercises", "6"],
  ["Modern Mechanical Vibrators", "2"], ["ECG Cycle Ergometers", "2"], ["ECG Treadmills", "2"], ["ECG Device", "3"], ["Dynamometers", "2"], ["High Frequency Chest Wall Oscillation (HFCWO) Device", "2"], ["High Frequency Chest Compression Machine", "2"], ["Nimbus Series Bed at least 1", "1"], ["Positive Expiratory Pressure (PEP) Mask with Manometer", "2"], ["Electro Flo 5000 Airway Clearance Device", "2"], ["Chest Vibrator", "2"], ["Children CompAir Lightweight Compressor Respiratory Nebulizer Inhale", "2"], ["Lumbar Vibratory Massage Pillow", "4"], ["Apex Exercise Pulley Set", "4"], ["Handycare Rollator", "5"], ["Mini Electric Exercise Bike", "2"], ["Mobile Frame Gait Walker", "3"], ["Fourier Intelligence Robot", "2"], ["Exercise Stair & Steps", "2 each"], ["Electronic Nebulizers", "2"], ["Peak Flow Meter", "4"], ["Respiratory Exerciser", "4"], ["Ambu Bag", "4"], ["Non-invasive Ventilators", "2"], ["In-supplators Device", "2"], ["Ex-supplators Device", "2"], ["Electrical Muscle Stimulators", "2"], ["Sand Bag 3kg, 2kg, 1kg", "2 each"], ["Hand Function Board", "4"], ["Hand Balls/Hand Exercisers", "5"], ["Wooden Stair Case", "4"], ["Portable Ultrasonic Therapy Machine", "2"], ["TENS/EMS", "2 each"], ["Infra-Red Lamps", "3"], ["Freezer (small size) for Ice making", "1"], ["Walking Aids (axillary crutches, elbow crutches, walking frame, tetrapod stick, tripod stick)", "5 each"], ["Weights/Sand bags", "5 each"], ["Lumbar and Cervical Traction Kits", "1 each"], ["Bandages", "10"], ["Giant Standing Mirrors", "1"], ["Utensils for Activities of Daily Living", "Many"], ["Weights", "3 each"], ["Warm Pack / Cold Pack", "5 each"], ["Assistive Products for Dressing", "3"], ["Assistive Products for Toileting", "3"], ["Dumbbells of Varying Sizes", "3 each"], ["Giant Mirror", "2"], ["Alarm", "Should be Placed in strategic locations"], ["Fire Extinguisher", "Should be Placed in strategic locations"], ["Blanket", "Should be Placed in strategic locations"], ["Intercom", "Should be Placed in strategic locations"], ["Fire Assembly Point", "Should be Placed in strategic locations"], ["Sand Bucket", "Should be Placed in strategic locations"]
]);

export const CLINICAL_QTY_MAP = buildMap([
  ["Treadmill", "4"], ["Traction units Cervical/Lumbar", "2"], ["Partial Body weight support system", "3"], ["Reciprocal Pulley", "4"], ["Tilt Bed/Supine Standers", "2"], ["Hand Exerciser", "2"], 
  ["Foam Wedges:", "3 each"], ["Foam Rolls:", "3 each"], ["Bicycle Ergometer (arm/legs)", "4"], ["Parallel Bar", "2"], ["Wall Bar", "3"], ["Finger Ladder", "2"], ["Shoulder Ladder", "2"], ["Shoulder Wheel", "2"], ["Wooden Staircase (firm/shake able)", "2"], ["Multi Gym", "2"], ["Exercise Mats", "12"], ["Exercise Plinths", "4"], ["Steppers", "12"], ["Recumbent Bicycle", "3"], ["Medicine/Exercise Balls", "12"], 
  ["Dumbbells:", "5 each"], ["TheraBands:", "5 each"], ["Sand Bags:", "5 each"], ["Giant Standing Mirrors", "3"], ["Quadriceps Drill/Bench", "2"], ["Wobble Boards", "6"], ["Precision Box", "3"], ["Wheel Chairs", "4"], ["Crutches (Elbow and Auxillary)", "3 of each"], ["Walking Frames", "3"], ["Walking Sticks, Quadrupod & Tripod", "3 of each"],
  ["Standing Infra-red Lamp (Luminous)", "3"], ["Electrical Muscle Stimulator", "3"], ["Therapeutic Ultrasound Machine", "2"], ["Transcutaneous Electrical Nerve Stimulator (TENS)", "20"], ["Shortwave Diathermy", "2"], ["Paraffin Wax Bath", "4"], ["Laser Therapy Machine", "2"], ["Portable Ultrasonic Therapy", "3"], ["Ice making Machine", "2"], ["Interferential Current Machine", "2"], ["Ultraviolet Radiation Machine", "2"], ["Micro wave therapy Machine", "2"], ["Infra-red Lamp (non - Luminous)", "3"], ["Hydrocollator Machine", "2"], ["Pneumatic Machine", "2"],
  ["Sphygmomanometer", "10"], ["Stethoscope", "10"], ["Goniometers", "4"], ["Spirometers", "4"], ["Peak Flow Meters", "4"], ["Hand Grip Dynamometer", "5"], ["Pain Rating Scale", "4"], ["One Stop Watch", "4"], ["Weighing Scale", "5"], ["Stadiometer", "4"], ["X-ray Viewing Box", "5"], ["Pedometer", "6"], ["Skin Fold Calipers", "4"], ["Heart Rate Monitor", "4"], ["Measuring Tape", "12"], ["Sensory processing Test Equipment", "3"], ["Cognitive Test Equipment", "3"], ["Pulse Oximeter", "8"], ["Body Mass Index Calculator", "4"], ["Periniometer", "4"], ["Reflex Hammer", "5"], ["Tongue Depressor (Pack)", "1 packet"], ["Tuning Fork (128Hz)", "3"], ["Two Test Tubes", "2 pairs"], ["Familiar Objects (e.g. paper clip, coin, marble)", "Several"], ["Thermometer", "5"], ["Cotton Ball or Cotton tipped Swab (Pack)", "1 packet"], ["Pen light", "4"], ["Cognitive Test Equipment (Parkinsons & Dementia)", "3"], ["Flashlight", "3"], ["Diagnostic Spirometer", "1"],
  ["Alarm", "Should be Placed in strategic locations"], ["Fire Extinguishers", "Should be available in strategic locations"], ["Blankets", "Many"], ["Fire Assembly Points", "Should be Placed in strategic locations"], ["Sand Buckets", "Should be Placed in strategic locations"], ["Clearly marked direction to Muster Points", "Should be Placed in strategic locations"],
  ["Face Masks (Pack)", "3 Packs (at any point in time)"], ["Disposable Gloves (Pack)", "3 Packs (at any point in time)"], ["Sputum Containers (Pack)", "3"], ["Sterilizing Unit", "1"], ["Autoclave", "1"], ["Antiseptic Solution (Pack)", "1 carton"], ["Washing Machine", "1"], ["Drying Machine", "1"],
  ["Towels", "12 (at any giving time)"], ["Mackintosh", "12 (at any giving time)"], ["Bedsheets", "12 sets"], ["Splinting Kit (static & Dynamic)", "12 sets"], ["Casting Kit – dynacast, POP, Soft bandage", "3 Packs (at any giving time)"], ["Topical Analgesic / ointments- cold and hot", "3 Packs (at any giving time)"], ["Creepe Bandage and gauze", "3 Packs (at any giving time)"], ["Contact medium - powder, lanolin oil", "3 Packs (at any giving time)"],
  ["Gait Trainers", "4"], ["Precision Boxes", "4"], ["Precision Toys", "4"], ["Giant Mirrors", "4"], ["Prone Standers", "4"], ["Standing Frames", "2"], ["Treatment Plinths", "2"], ["Therapy Balls/Medicine Balls", "6"], ["Posterior Walkers", "3"], ["Frenkel Mats", "4"], ["Paediatric Treadmill", "1"], ["Resistance Bands:", "3 each"], ["Paediatric Crutches", "3"], ["Paediatric Tilt Bed", "1"], ["Supportive Garment", "6"], ["Stabilization Belts", "6"], ["Everyday Objects for ADL", "several"], ["Adapted eating and drinking products", "2 sets"], ["Stools/small benches of varying heights", "5"], ["Resistive Exercise Putty", "3"], ["Television Set", "1"], ["Partial Body Weight Support system with Harness", "2"], ["Paediatric (dexterity training) cones", "12"],
  ["Gait Belts", "4"], ["3 by 4 feet wheeled Walker", "3"], ["Neuro Com Balance Master", "2"], ["Transfer Boards", "4"], ["Slide Sheets", "4"], ["Pillows", "10"], ["Arm Activity Kit", "2"], ["Upper limb Work Station", "2"], ["Upper limb Support", "4"], ["Small Benches of varying heights", "6"], ["Rollators", "3"], ["Balance Board/Cushion", "4"], ["Resistive Exercise Putty (dough)", "3"], ["Exercise Therapy Plinths", "3"], ["Stools", "6"],
  ["Lumbar Traction Bed", "1"], ["Precision Boards", "4"], ["Cervical Traction Kit", "2"], ["Orthoses Kit", "2"], ["Stabilization/Mobilization Belts", "4"], ["Hot & cold Packs", "6"],
  ["Vaginal Cones (diff. sizes)", "5"], ["Screen", "5"], ["Portable TENS", "4"], ["Vaginal & Anal Sensors", "4"], ["Vaginal Weights", "5"], ["Irrigation therapy devices:", "4"], ["Pessaries- (trained therapist for fitting)", "4"], ["Intravaginal devices for stress urinary incontinence:", "4"], ["Vibrators", "4"], ["Pelvic band", "4"], ["Kegel balls", "6"], ["Dilators (individualized)", "2 sample"], ["Biofeedback Machine", "1"],
  ["Suction Machine", "2"], ["High frequency chest wall Oscillation Device (HFCWO)", "2"], ["High frequency Chest Compression Machine", "2"], ["Nimbus Series Bed", "1"], ["Positive Expiratory Pressure (PEP) Mask with Manometer", "3"], ["Positive Expiratory Pressure Therapy (PEP)", "3"], ["Electro Flo 5000 Airway Clearance Device", "4"], ["Compressor Nebulizer", "2"], ["Lumbar Vibratory Massage Pillow", "2"], ["Mobile frame Gait Walker", "2"], ["Electronic Nebulizer", "2"], ["Ambu Bag", "6"], ["Noninvasive Ventilators", "4"], ["In sufflator Machine", "2"], ["Ex sufflator Machine", "2"], ["Elliptic Ergometer", "2"], ["Treadmill with ECG", "1"], ["Accapella Device", "3"], ["Flutter Device", "3"], ["Postural Drainage Bed", "1"], ["Trampoline", "2"],
  ["Electrical Muscle Stimulators", "2"], ["Cervical Traction Kit ", "1"], ["Lumbar Traction Kit", "1"], ["Therapeutic Ultrasound Machine ", "2"], ["Sand Bags:", "2 each"], ["Transcutaneous Electrical Nerve Stimulator ", "5"], ["Plinths ", "5"], ["Bicycle Ergometer ", "4"], ["Shortwave Diathermy ", "2"], ["Wall Bars ", "4"], ["Finger Ladder ", "4"], ["Shoulder Wheel ", "4"], ["Standing Mirror ", "4"], ["Hand Function Board ", "4"], ["Hand Balls, Hand Exercises ", "5"], ["Wooden Stair Case", "4"], ["Standing Infrared Machine ", "1"],
  ["TENS", "5"], ["Hot and Cold Packs", "6"], ["Utensils for activities of daily living", "Make available"], ["Resistance Bands", "10"], ["Weights", "10"], ["Exercise Ball", "6"], ["Assistive products for dressing", "Make available"], ["Assistive products for toileting", "Make available"], ["Equipment for sport and recreational activities", "Make available"], ["Steppers", "6"],
  ["Dumb Bells:", "4 each"], ["Casting Kit", "12 sets"], ["Splinting Kit", "12 sets"], ["Orthoses kit", "12 sets"], ["Mobile Mirrors", "1"], ["Assistant Support Belt", "5"], ["Ramps", "2"], ["Stackable Steps", "5"], ["Training Stairs", "1"], ["Cycle Ergometer with and without arm", "2 each"], ["Arm activity Kit (CIMT, Bimanual activities)", "Make available"], ["Utensils for activity of daily living", "Make available"], ["Therapeutic Toys", "Make available"], ["Walking Aids- crutches, walking sticks, frames rollators", "2 of each"], ["Wheelchairs", "2"],
  ["Balance Board/Cushion", "3"], ["Cycle Ergometer (arm or leg)", "2"], ["Video Recording Devices", "4"], ["Weights:", "3 each"], ["Giant Mirror", "1"],
  ["Portable Ultrasonic Therapy Machine", "4"], ["TENS/EMS", "4"], ["Standing Infra-Red Lamps", "3"], ["Freezer (small size) for Ice making", "4"], ["Walking Aids (crutches)", "5"], ["Weights/Sand Bags:", "Different sizes"], ["Cervical Traction Machine", "1"], ["Hand Exercisers", "4"], ["Bandages", "10"],
  ["Standard Hydrotherapy Pool", "1"], ["Aquatic Treadmill", "1"], ["Aquatic Ergometer", "1"], ["Life jackets", "Make available"]
]);

export const AUDIOLOGY_ACADEMIC_QTY_MAP = buildMap([
  ["Hospital Bed Space", "250 minimum"],
  ["Embalmed bodies", "1 cadaver per set of 8 students"], ["Anatomage", "1"], ["Equipment Trolleys", "3"], ["Electric Embalming Machine", "1"], ["Bone Cutting Equipment - Electric Saw/Drill", "2"], ["Articulated and Unarticulated Skeletons", "5"], ["X-ray Viewing Boxes", "3"], ["Air-Conditions for the Dissecting Rooms and Air Extractors.", "4"], ["Models", "5"], ["Slide for Sections", "Many"], ["Slide Projectors", "3"], ["Toilet Facilities:", "Gender sensitive"], ["Changing Room", "2"], ["Shower Room etc.", "1"],
  ["Microtome", "2"], ["Rotary/Sledge Microtome Knives", "3"], ["Light Microscopes Microtome", "1 per 2 students"], ["Vacuum Pump Dissecting Microtome", "3"], ["Cryostat with Microtome", "3"], ["Teaching Microscope", "3"], ["Electron Microscope", "1 per 2 students"], ["Slides", "Many"], ["Centrifuge", "6"], ["Ultracentrifuge", "2"], ["Electronic Balances", "2"], ["Heating Block", "8"], ["Vacuum Pumps", "2"], ["Spectrophotometer", "1 per 20 students"], ["PH. Metres", "1 per 20 students"], ["Thermostatic Water Bath", "1"], ["Bunner", "3 per bench"], ["Test Tube varying size", "Many"], ["Distiller", "3"],
  ["Spirometer", "1 per 20 students"], ["Vitalograph", "1 per 20 students"], ["Polygraph", "1"], ["Peak Flow Metre", "1 per 20 students"], ["Gas Metre", "2"], ["Ecg Machine", "4"], ["Spectrophotometers", "1 per 20 students"], ["Physiograph Recorder Transducers", "1 per 20 students"], ["Oscilloscopes", "4"], ["Centrifuges", "6"], ["Blood Gas Callipers", "2"], ["Audiometer", "2"], ["Water Baths", "2"], ["Electronic Weighing Balance Scale", "2"], ["Flame Photometer", "4"], ["Microcentrifuge", "2"], ["Water Distiller", "5"], ["Bicycle Ergometer", "3"], ["Stethoscope/ Sphygmomanometre", "12"], ["Snelle's Chart", "5"],
  ["Diagnostic Audiometer", "1"], ["Screening Audiometer", "1"], ["Portable Audiometer", "1"], ["Sound Treated Booth", "1"], ["Supra-Aural Headphones", "2"], ["Bone Vibrator", "1"], ["Patient Response Button", "1"], ["Speech Microphone/Talk Forward Mic", "1"], ["Sound Field Speakers", "1"], ["Otoscope", "4"], ["Tunning Forks (Sets)", "2 sets"], ["Cerumen Management Kit (Sets)", "2 sets"], ["Diagnostic Tympanometer", "1"], ["Immitance Meter", "2"], ["Eustachian Tube Function Module", "2"], ["Probe Tips And Ear Couplers", "2"], ["OAE Machine(TEOAE,DPOAE)", "1"], ["ABR Machine", "1"], ["AABR Newborn Screener", "1"], ["ASSR Machine", "1"], ["Electrodes (Sets)", "2 sets"], ["Sin Prep Gel (Set)", "1 set"], ["Disposable Ear Tips (Sets)", "2 sets"], ["Speech Perception Software", "1"], ["Speech Audiometry Test Materials (Set)", "1 set"], ["Auditory Processing Test Materials (Sets)", "2 sets"], ["Tinnitus Matching Modules", "1"],
  ["Face Masks (Packs)", "Packs"], ["Disposable Gloves (Packs)", "Packs"], ["Sputum Containers (Packs)", "Packs"], ["Sterilizing Unit", "1"], ["Autoclave", "1"], ["Antiseptic Solution (Packs)", "Packs"], ["Washing Machine", "1"], ["Drying Machine", "1"],
  ["Clinical/Diagnostic Audiometer", "1"], ["Portable Screening Audiometer", "1"], ["Sound-Treated Room", "1"], ["Insert Earphones (Sets)", "Sets"], ["Acoustic Reflex Analyzer", "1"], ["OAE Machine", "1"], ["ABR/ASSR System", "1"], ["Tunning Fork (Sets)", "Sets"], ["Laptop And Audiology Software", "1"], ["Printer / Recording System", "1"], ["Calibration Tools (Set)", "1 set"], ["Cerumen Management Kit (Set)", "1 set"],
  ["Oae", "1"], ["AABR /New-born Hearing Screening", "1"], ["Diagnostic ABR/ASSR", "1"], ["VRA Setup(lights, animated toys , video reinforcement) (Set)", "1 set"], ["Conditioned Play Audiometry Toys (Set)", "1 set"], ["Sound Filled Speakers", "2"], ["Paediatric Insert Earphones", "2"], ["Distraction Toys (Set)", "1 set"], ["Reinforment Box", "2"], ["Visual Reward Display", "2"], ["Paediatric Hearing And Verification Tools", "2"], ["Developmental Screening Materials (Set)", "1 set"],
  ["Otoscope/ Videoscope", "3"], ["Tympanometer/Immitance Meter", "1"], ["Lptop And Audilogy Software", "1"],
  ["Hearing Aids (BTE,RIC,ITE,CIC) (Set)", "1 set"], ["Hearing Aid Programing Software", "1"], ["Hearing Aid Programmer", "1"], ["Real Ear Measurement(REM)System", "2"], ["Hearing Aid Analyser/Test Box", "1"], ["Earmold Impression Syringe (Set)", "1 set"], ["Ear Tips And Domes (Set)", "1 set"], ["Hearing Aid Batteries/Charges (Set)", "1 set"], ["FM Systems /Remote Microphone Systems", "1"], ["Loop System", "1"], ["Auditory Training Software", "1"], ["Speech Perception Test Materials (Set)", "1 set"], ["Counselling Materials (Set)", "1 set"], ["Communication Strategy Hand-outs", "3"], ["Apparatus for balance rehabilitation testing", "2"],
  ["ENG/VNG System", "1"], ["Infrared Video Goggles", "1"], ["Frenzel Goggles", "1"], ["Caloric Irrigator", "1"], ["Rotary Chair", "2"], ["VEMP Machine", "1"], ["Computer and Balance Software", "1"], ["Posturography System", "1"], ["Foam Balance Pad", "1"], ["Gait Assessment Walkway", "1"], ["Dix-Hall pike Couch/Examination", "2"], ["Safety Harness", "2"], ["Vestibular Rehab Exercise Tools (Set)", "1 set"],
  ["Cochlear Implant Programing Software", "1"], ["Mapping", "1"], ["Speech Processor", "1"], ["Transmitting Coil", "1"], ["Telemetry/ECAP System", "1"], ["CI Troubleshooting Kit (Set)", "1 set"], ["Battery and Charger System:", "3 each"], ["Bone-Anchored Hearing Device Programming Kit", "2"], ["Laptop Workstation", "1"], ["Intaoperative Monitoring Interface(Advance Centres)", "1"], ["Rehabilitation Listening Materials (Set)", "1 set"],
  ["Mobile Audiometric Booth", "1"], ["Noise Dosimeter", "1"], ["Sound Level Meter", "1"], ["Octave Band Analyzer", "1"], ["Hearing Protection Fit-Testing System", "1"], ["Earplugs And Ear Earmuffs", "2"], ["Hearing Conservation Software", "1"], ["Record Management Software", "1"], ["Worker Counselling Materials (Set)", "1 set"], ["Potable Otoscope", "5"], ["Industrial Noise Survey Kit (Set)", "1 set"],
  ["High-Frequency Audiometer", "1"], ["Loudness Discomfort Level (LDL) Tools", "4"], ["Tinnitus Questionnaires (THI,TFI)", "3"], ["Sound Therapy Generators", "2"], ["Tinnitus Maskers", "3"], ["Combination Hearing Aids (Set)", "1 set"], ["White Noise Generators", "1"], ["Counselling Software/CBT Materials", "5"], ["Relaxation Audio Library", "1"], ["Public Health Screening Audiometer", "1"], ["OAE Screener", "1"], ["Noise Awareness Education Kits (Set)", "1 set"], ["Community Outreach IEC Materials (Set)", "1 set"], ["Ear Protection Demonstration Kits (Set)", "1 set"],
  ["Alarm", "Should be Placed in strategic locations"], ["Fire Extinguisher", "Should be Placed in strategic locations"], ["Blanket", "Should be Placed in strategic locations"], ["Intercom", "Should be Placed in strategic locations"], ["Fire Assembly Point", "Should be Placed in strategic locations"], ["Sand Bucket", "Should be Placed in strategic locations"]
]);

export const AUDIOLOGY_CLINICAL_QTY_MAP = buildMap([
  ["Diagnostic Audiometer", "1"], ["Screening Audiometer", "1"], ["Portable Audiometer", "1"], ["Sound Treated Booth", "1"], ["Supra-Aural Headphones", "2"], ["Bone Vibrator", "1"], ["Patient Response Button", "1"], ["Speech Microphone/Talk Forward Mic", "1"], ["Sound Field Speakers", "1"], ["Otoscope", "4"], ["Tunning Forks (Sets)", "2sets"], ["Cerumen Management Kit (Sets)", "2sets"], ["Diagnostic Tympanometer", "1"], ["Immitance Meter", "2"], ["Eustachian Tube Function Module", "2"], ["Probe Tips And Ear Couplers", "2"], ["OAE Machine(TEOAE,DPOAE)", "1"], ["ABR Machine", "1"], ["AABR New-born Screener", "1"], ["ASSR Machine", "1"], ["Electrodes (Sets)", "2sets"], ["Sin Prep Gel (Set)", "1set"], ["Disposable Ear Tips (Sets)", "2sets"], ["Speech Perception Software", "1"], ["Speech Audiometry Test Materials (Set)", "1set"], ["Auditory Processing Test Materials (Sets)", "2sets"], ["Tinnitus Matching Modules", "1"],
  ["Alarm", "Should be Placed in strategic locations"], ["Fire Extinguisher", "Should be Placed in strategic locations"], ["Blanket", "Many"], ["Intercom", "-"], ["Fire Assembly Point", "Should be Placed in strategic locations"], ["Sand Bucket", "Should be Placed in strategic locations"], ["Clearly marked direction to Muster Point", "Should be Placed in strategic locations"],
  ["Face Masks (Packs)", "3 Packs (at any point in time)"], ["Disposable Gloves (Packs)", "3 Packs (at any point in time)"], ["Sputum Containers", "3"], ["Sterilizing Unit", "1"], ["Autoclave", "1"], ["Antiseptic Solution (Carton/Pack)", "1 carton"], ["Washing Machine", "1"], ["Drying Machine", "1"],
  ["Disposable Electrode Pads", "20"], ["Acohol Swab", "25"], ["Probe Tip Seals", "30"], ["Aural Impression Syringe", "20"], ["Tissue Papers", "20"], ["Hearing Aid Batteries (Packs)", "5packs"], ["Clearing Wipes", "30"], ["Cochlear Implant Cable Cover", "20"], ["Silicone Impression Material", "10"], ["Lubricants", "10"], ["Marking Pencils", "15"], ["Disposable Trimming Blades (Packs)", "2packs"], ["Ear Tips", "10"], ["Retention Locks", "10"], ["Clearing Brushes", "5"], ["Impression Blocks", "10"],
  ["Clinical/Diagnostic Audiometer", "1"], ["Portable Screening Audiometer", "1"], ["Sound-Treated Room", "1"], ["Insert Earphones (Sets)", "sets"], ["Speech Microphone", "2"], ["Acoustic Reflex Analyzer", "1"], ["OAE Machine", "1"], ["ABR/ASSR System", "1"], ["Tunning Fork (Sets)", "stes"], ["Laptop And Audiology Software", "1"], ["Printer / Recording System", "1"], ["Calibration Tools (Set)", "set"], ["Cerumen Management Kit (Set)", "set"],
  ["OAE", "1"], ["AABR /New-born Hearing Screening", "1"], ["Diagnostic ABR/ASSR", "1"], ["VRA Setup(lights, animated toys , video reinforcement) (Set)", "set"], ["Conditioned Play Audiometry Toys (Set)", "set"], ["Sound Filled Speakers", "2"], ["Paediatric Insert Earphones", "2"], ["Distraction Toys (Set)", "set"], ["Reinforment Box", "2"], ["Visual Reward Display", "2"], ["Pediatric Hearing And Verification Tools", "2"], ["Developmental Screening Materials (Set)", "set"],
  ["Otoscope/ Videoscope", "3"], ["Tympanometer/ Immitance Meter", "1"], ["Lptop And Audilogy Software", "1"], ["Calibration Tools (Sets)", "sets"], ["Cerumen Management Kit (Sets)", "sets"],
  ["Hearing Aids (BTE,RIC,ITE,CIC) (Set)", "set"], ["Hearing Aid Programing Software", "1"], ["Hearing Aid Programmer", "1"], ["Real Ear Measurement(REM)System", "2"], ["Hearing Aid Analyser/Test Box", "1"], ["Earmold Impression Syringe (Set)", "set"], ["Ear Tips And Domes (Set)", "set"], ["Hearing Aid Batteries/Charges (Set)", "set"], ["FM Systems /Remote Microphone Systems", "1"], ["Loop System", "1"], ["Auditory Training Software", "1"], ["Speech Perception Test Materials (Set)", "set"], ["Counselling Materials (Set)", "set"], ["Communication Strategy Hand outs", "3"], ["Assistive Listening Device", "2"],
  ["ENG/VNG System", "1"], ["Infrared Video Goggles", "1"], ["Frenzel Goggles", "1"], ["Caloric Irrigator", "1"], ["Rotary Chair", "2"], ["VEMP Machine", "1"], ["Computer And Balance Software", "1"], ["Posturography System", "1"], ["Foam Balance Pad", "1"], ["Gait Assessment Walkway", "1"], ["Dix-Hall pike Couch/Examination", "2"], ["Safety Harness", "2"], ["Vestibular Rehab Exercise Tools", "set"],
  ["Cochlear Implant Programing Software", "1"], ["Mapping", "1"], ["Speech Processor", "1"], ["Transmitting Coil", "1"], ["Telemetry/ECAP System", "1"], ["CI Troubleshooting Kit (Set)", "set"], ["Battery and Charger System:", "3each"], ["Bone-Anchored Hearing Device Programming Kit", "2"], ["Laptop Workstation", "1"], ["Intraoperative Monitoring Interface(Advance Centres)", "1"], ["Rehabilitation Listening Materials (Set)", "Set"],
  ["Mobile Audiometric Booth", "1"], ["Noise Dosimeter", "1"], ["Sound Level Meter", "1"], ["Octave Band Analyzer", "1"], ["Hearing Protection Fit-Testing System", "1"], ["Earplugs And Ear Earmuffs", "2"], ["Hearing Conservation Software", "1"], ["Record Management Software", "1"], ["Worker Counselling Materials (Set)", "set"], ["Potable Otoscope", "5"], ["Industrial Noise Survey Kit (Set)", "set"],
  ["Clinical Audiometer", "1"], ["High-Frequency Audiometer", "1"], ["Tinnitus Matching Modules", "3"], ["Loudness Discomfort Level (LDL) Tools", "4"], ["Tinnitus Questionnaires (THI,TFI)", "3"], ["Sound Therapy Generators", "2"], ["Tinnitus Maskers", "3"], ["Combination Hearing Aids (Set)", "set"], ["White Noise Generators", "1"], ["Counselling Software/CBT Materials", "5"], ["Relaxation Audio Library", "1"], ["Public Health Screening Audiometer", "1"], ["OAE Screener", "1"], ["Noise Awareness Education Kits (Set)", "set"], ["Community Outreach IEC Materials (Set)", "set"], ["Ear Protection Demonstration Kits (Set)", "set"]
]);

export const OCCUPATIONAL_THERAPY_ACADEMIC_QTY_MAP = buildMap([
  ["Hospital Bed Space", "250 minimum"],
  ["Embalmed Bodies", "1 cadaver per set of 6 students"], ["Anatomage Table", "1"], ["Equipment Trolleys", "3"], ["Electric Embalming Machine", "1"], ["Bone Cutting Equipment - Electric Saw/Drill", "2"], ["Articulated and Unarticulated Skeletons", "5"], ["X-ray Viewing Boxes", "3"], ["Air-conditioners for the Dissecting Rooms and Air Extractors", "4"], ["Models", "5"], ["Slide for Sections", "Many"], ["Slide Projectors", "3"], ["Toilet Facilities:", "Gender sensitive"], ["Changing Room", "2"], ["Shower Room", "1"],
  ["Microtome", "2"], ["Rotary/Sledge Microtome Knives", "3"], ["Light Microscopes", "1 per 2 students"], ["Vacuum Pump Dissecting Microtome", "3"], ["Cryostat with Microtome", "3"], ["Teaching Microscope", "3"], ["Electron Microscope", "1 per 2 students"], ["Slides", "Many"],
  ["Centrifuge", "6"], ["Ultracentrifuge", "2"], ["Electronic Balances", "2"], ["Heating Block", "8"], ["Vacuum Pumps", "2"], ["Spectrophotometer", "1 per 10 students"], ["pH Metres", "1 per 5 students"], ["Thermostatic Water Bath", "1"], ["Burner", "3 per bench"], ["Test Tubes (varying sizes)", "Many"], ["Distiller", "3"],
  ["Spirometer", "1 per 5 students"], ["Vitalograph", "1 per 5 students"], ["Polygraph", "1"], ["Peak Flow Metre", "1 per 5 students"], ["Gas Metre", "2"], ["ECG Machine", "4"], ["Spectrophotometers", "1 per 5 students"], ["Physiograph Recorder Transducers", "1 per 5 students"], ["Oscilloscopes", "4"], ["Centrifuges", "6"], ["Audiometer", "2"], ["Water Baths", "2"], ["Electronic Weighing Balance Scale", "2"], ["Flame Photometer", "4"], ["Microcentrifuge", "2"], ["Water Distiller", "5"], ["Stethoscopes/Sphygmomanometers", "12"], ["Electron Microscope", "1 per 2 students"], ["Teaching Microscope", "3"], ["Slides", "Many"], ["Snellen's Chart", "5"],
  ["Relaxation Chair", "3"], ["Floor Sitter", "2"], ["Stand-in Frame", "3"], ["Stand-in Table", "2"], ["Corner Seat", "2"], ["Standing Frames", "2"], ["Mat Platforms", "3"], ["Treatment Tables", "3"], ["Tilt Tables", "1"], ["Stools", "2"], ["Carts", "2"], ["Screens", "2"], ["Mirrors (full length)", "2"], ["Parallel Bars", "1"], ["Stairs (training)", "1"], ["Work Hardening Station", "1"], ["Trays and Accessories", "5"], ["Ramps", "3"], ["Therapeutic Gloves", "3"], ["Weighing Scales", "3"], ["Convalescent Recliners", "1"],
  ["Steadiness Tester (hole type)", "2"], ["Pencil Maze Test Board", "2"], ["Tremor Quantifier", "1"], ["Hand Dynamometer", "3"], ["Pinch Gauge / Pinch Meter", "3"], ["Strength Evaluation System", "2"], ["Goniometer", "3"], ["Finger Dexterity Test Board", "1"], ["Key Hole Test Board", "1"], ["Counting and Colour Sorting Beads Set", "1"], ["Tape Measure", "4"], ["Sensory Pins", "4"], ["Tuning Fork", "4"], ["Reflex Hammer", "4"], ["Standardized Outcome Measure Forms/Kits", "4"], ["Stopwatch", "4"], ["Cognitive Assessment Kit (e.g. MMSE, MoCA, LOTCA)", "2"], ["Sensory Profile Assessment Kit", "2"], ["Visual Perception Test Kit", "2"],
  ["Reachers", "1"], ["Dressing Aids (button hooks, sock aids, dressing sticks)", "4"], ["Mobility Aids (Walker, Quad cane, Standard cane)", "3"], ["Adaptive Scissors", "2"], ["Book Holder", "2"], ["Writing Aids (built-up grips, weighted pens)", "2"], ["Door Latch Practice Frame Set", "1"], ["Electro-equipment Practice Frame Set", "1"], ["Dressing Practice Frame Set", "1"], ["Eating Aids with Adapted Utensils", "1 set"], ["Eating Aids with Adapted Utensils (Set)", "1 set"], ["ADL Kits", "2"], ["Span Board", "1"], ["ADL Practice Board", "2"], ["Resistive Bars", "3"], ["Electric Iron", "2"], ["Adapted Clothing for Training", "3 sets"], ["Adapted Clothing for Training (Sets)", "3 sets"], ["Long-handled Sponge", "2"], ["Bath Bench / Shower Chair", "1"], ["Raised Toilet Seat", "1"], ["Commode Chair", "1"], ["Grab Bars (training)", "2"], ["Non-slip Mat", "2"],
  ["Simulated Bathing Station", "1"], ["Simulated Toileting Station", "1"], ["Grooming Station (mirror, sink, supplies)", "1"], ["Nail Care Set", "1"], ["Oral Care Practice Set", "1"], ["Hair Care Tools", "1 set"], ["Hair Care Tools (Set)", "1 set"],
  ["Plates and Bowls", "1 set"], ["Plates and Bowls (Set)", "1 set"], ["Cups and Drinking Aids", "1 set"], ["Cups and Drinking Aids (Set)", "1 set"], ["Adapted Utensils", "1 set"], ["Adapted Utensils (Set)", "1 set"], ["Gas Cooker", "1"], ["Self-feeders and Arm Supports", "1"], ["Over-bed Tables", "1"], ["Dycem (Non-slip) Products", "1 set"], ["Dycem (Non-slip) Products (Set)", "1 set"], ["Dining Accessories", "1 set"], ["Dining Accessories (Set)", "1 set"], ["Plate Rack", "1"], ["Mixer", "1"], ["Blender", "1"], ["Adapted Cutting Board (one-handed)", "1"], ["Adapted Jar Opener", "1"], ["Reach Extender", "1"], ["Kitchen Apron (adaptive)", "2"],
  ["Tactile Stimulators (textures, brushes, feathers)", "5"], ["Visual Stimulators (light tubes, projector toys)", "5"], ["Peg Boards", "5"], ["Target Game", "1"], ["Basic Balance Beam", "1"], ["Balance Boards", "2"], ["Dart Board", "1"], ["Ball Pool", "1"], ["Puzzles", "5"], ["Multi-activity Work Station", "1"], ["Mushroom Boards", "1"], ["Pegs and Shapes Set", "1"], ["Pinch Tree Board", "1"], ["Size Perception Square Board Set", "5"], ["Geometric Shape Form Board Set", "1"], ["Foot Placement Ladder", "1"], ["Equilibrium Board", "1"], ["Trampoline", "1"], ["Building Blocks", "3"], ["Visual Cues and Illustration Materials", "3"], ["Puzzle Game Board Set", "3"], ["Play Dough", "3"], ["Cone Board", "2"], ["Weighted Vest / Blanket", "2"], ["Therapy Swing (vestibular)", "1"], ["Resonance Board", "1"], ["Fibre Optic Lights", "1 set"], ["Fibre Optic Lights (Set)", "1 set"], ["Bubble Tube", "1"],
  ["Virtual Reality System with Screen", "1"], ["Driving Simulator Setup with Screen", "1"], ["Computer Set", "1"], ["Work Hardening System", "1"], ["Work Conditioning Equipment", "1"], ["Ergonomic Workstation (adjustable)", "1"], ["Job Simulation Kits", "1"], ["Lifting Boxes (varied weights)", "1 set"], ["Lifting Boxes (varied weights) (Set)", "1 set"], ["Pegboard Assembly Task Kits", "2"], ["Fine Motor Work Tasks (sorting, assembly)", "3"],
  ["Shoulder Supports and Slings", "1 each (assorted sizes)"], ["Elbow Supports", "1 each (assorted sizes)"], ["Upper Extremity Support Products", "1 set"], ["Upper Extremity Support Products (Set)", "1 set"], ["Wrist Supports", "1 each (assorted sizes)"], ["Cervical Collars (soft and rigid)", "1 each"], ["Clavicle Brace", "1"], ["Thoracic Brace", "1"], ["Cock-up Splints", "1 each (sizes)"], ["Resting Hand Splints", "1 each (sizes)"], ["Thumb Spica Splints", "1 each (sizes)"], ["Dynamic Hand Splints", "1 each"], ["Splint-fabrication Materials (low-temperature thermoplastics)", "1 set"], ["Splint-fabrication Materials (low-temperature thermoplastics) (Set)", "1 set"], ["Heat Gun / Splint Pan", "1"], ["Splint Strapping Materials", "1 set"], ["Splint Strapping Materials (Set)", "1 set"],
  ["Ankle, Foot and Heel Supports", "1 each"], ["Knee Supports", "1 each"], ["Back Supports / Lumbosacral Belts", "1 each"], ["Bed Positioning and Safety Products (pillows, wedges)", "1 set"], ["Bed Positioning and Safety Products (pillows, wedges) (Set)", "1 set"], ["Compression Stockings", "2 pairs"], ["Compression Stockings (Pairs)", "2 pairs"], ["Edema-management Products (pumps, sleeves)", "2"], ["Canes (standard, quad)", "1 each"], ["Crutches (axillary, elbow)", "1 each pair"], ["Crutches (axillary, elbow) (Pairs)", "1 each pair"], ["Scar Management Products / Gel Sheets", "1 set"], ["Scar Management Products / Gel Sheets (Set)", "1 set"], ["Ergonomic Adjusters (chairs, tables, toilets)", "1 set"], ["Ergonomic Adjusters (chairs, tables, toilets) (Set)", "1 set"], ["Therapeutic Taping (rigid, elastic)", "1 set"], ["Therapeutic Taping (rigid, elastic) (Set)", "1 set"], ["Pelvic Belts", "1"],
  ["Sanding Unit (reciprocal/semi-circular/vertical/overhead)", "3"], ["Sand and Water Table", "2"], ["Multi-purpose Wheel (shoulder)", "1"], ["Flexion/Extension/Pronation/Supination Apparatus", "1"], ["Inclined Tapered Balance Beam", "1"], ["Slanted Walking Board", "1"], ["Strength Training Equipment (sand bags 1-5 kg)", "1 set"], ["Strength Training Equipment (sand bags 1-5 kg) (Set)", "1 set"], ["Prone Crawling Board", "1"], ["Vestibular Board", "1"], ["Vestibular Swing System", "1"], ["Exercise Mats", "3"], ["Positioning Bolsters", "3"], ["Exercise Bands (resistive: light/medium/heavy)", "3 each"], ["Exercise Balls (varying sizes)", "3"], ["Weights (Dumbbells: 1-5 kg)", "3 each pair"], ["Weights (Dumbbells: 1-5 kg) (Pairs)", "3 each pair"], ["Balance Boards / Wobble Boards", "1"], ["Therapy Putty (varied resistances)", "4"], ["Hand Strengthener Devices", "4"], ["Pulleys / Wall System", "1"], ["Bungee Cords (therapy)", "1 set"], ["Bungee Cords (therapy) (Set)", "1 set"], ["Rebounder", "1"], ["Trampoline", "1"], ["Soft Ball", "1"], ["Skating Board", "1"], ["Range of Motion Arc", "1"], ["Spiral Arc", "1"], ["Peg Board", "1"], ["Standing Frame", "1"], ["Crawling Board", "1"], ["Abductor Ladder", "1"], ["Wheelchair", "2"], ["Finger Ladder", "2"], ["Shoulder Wheel", "2"],
  ["Paediatric Treatment Tables", "2"], ["Paediatric Seating & Mobility Aids", "2"], ["Toileting and Bathing Aids (paediatric)", "1"], ["Therapy Pool (optional)", "1"], ["Bolsters", "3"], ["Peanut/Pea Balls", "3"], ["Standers", "1"], ["Gait Trainers", "1"], ["Paediatric Walkers", "2"], ["Paediatric Mobility Aids", "2"], ["Paediatric Outcome Measure Tools", "4"], ["Adaptive Feeding/Eating Equipment (paediatric)", "2"], ["Sensory Toys / Manipulatives", "10"], ["Therapy Wedges (paediatric)", "3"], ["Paediatric Splints (resting, functional)", "5 each"], ["Adaptive Seating Cushions", "3"],
  ["Relaxation Chairs/Recliners", "3"], ["Group Activity Tables", "2"], ["Art and Craft Supplies (paints, brushes, canvas, paper)", "1 set"], ["Art and Craft Supplies (paints, brushes, canvas, paper) (Set)", "1 set"], ["Music/Audio Equipment", "1"], ["Cognitive Stimulation Materials (board games, card games, puzzles)", "5"], ["Stress Balls / Fidget Items", "10"], ["Mindfulness/Meditation Cushions", "5"], ["Journals and Writing Supplies", "1 set"], ["Journals and Writing Supplies (Set)", "1 set"], ["Anger Management Materials", "1 set"], ["Anger Management Materials (Set)", "1 set"], ["Social Skills Training Resources", "1 set"], ["Social Skills Training Resources (Set)", "1 set"], ["Video Recording Devices (for feedback)", "1"], ["Mirror (full length)", "2"], ["Yoga Mats", "5"],
  ["Walking Aids (walker, quad cane, tetrapod)", "5 each"], ["Wheelchair (standard)", "3"], ["Wheelchair (reclining)", "1"], ["Bath Chair / Shower Chair", "3"], ["Commode Chair", "3"], ["Adaptive Eating Utensils", "5 sets"], ["Adaptive Eating Utensils (Sets)", "5 sets"], ["Memory Aids and Cognitive Games", "5"], ["Large-print Reading Materials", "1 set"], ["Large-print Reading Materials (Set)", "1 set"], ["Magnifiers", "5"], ["Hearing Aid Demonstration Devices", "2"], ["Pressure-relief Cushions", "5"], ["Lumbar/Cervical Pillows", "5"], ["Stairs (low-rise practice)", "1"], ["Standing Mirror", "2"], ["Gait Belts", "5"], ["Bedside Commode", "2"],
  ["Portable ADL Kits", "2"], ["Portable Assessment Kits (cognitive, functional)", "2"], ["Mobile/Portable Splinting Materials", "1 set"], ["Mobile/Portable Splinting Materials (Set)", "1 set"], ["Mobile Sensory Stimulation Kit", "1"], ["Educational/Information Materials (handouts, posters)", "1 set"], ["Educational/Information Materials (handouts, posters) (Set)", "1 set"], ["Demonstration/Teaching Models", "3"], ["Adaptive Equipment Samples for Home Adaptation", "1 set"], ["Adaptive Equipment Samples for Home Adaptation (Set)", "1 set"], ["Walking Aids (assorted)", "3 each"], ["Wheelchair (portable)", "1"], ["Home-modification Demonstration Materials", "1 set"], ["Home-modification Demonstration Materials (Set)", "1 set"],
  ["High-impedance Mannequin", "1"], ["Manual Mannequins", "10"], ["Simulation Beds (cubicle layout)", "10"], ["Audiovisual Recording Setup", "1"], ["Vital Signs Simulator", "1"],
  ["Goniometers", "4"], ["Sphygmomanometer / Stethoscope", "4 each"], ["Spirometers", "2"], ["Peak Flow Meters", "2"], ["Skin Fold Callipers", "2"], ["Stopwatches", "4"], ["Hand Grip Dynamometer (digital)", "5"], ["Pinch Gauge", "5"], ["Weighing Scale (wheelchair accessible)", "3"], ["Pain Rating Scale Materials", "4"], ["Sensory Processing Test Equipment", "2"], ["Heart Rate Monitor", "5"], ["Measuring Tape", "10"], ["Cognitive Test Equipment", "5"], ["Stadiometer", "1"], ["Body Mass Index Calculator", "5"], ["Pulse Oximeter", "5"], ["Reflex Hammer", "5"], ["Tongue Depressor", "Packs"], ["Tongue Depressor (Packs)", "Packs"], ["Tuning Fork (128 Hz)", "5"], ["Familiar Objects (paper clip, coin, marble) - stereognosis", "4 sets"], ["Familiar Objects (paper clip, coin, marble) - stereognosis (Sets)", "4 sets"], ["Pen Light", "5"], ["Thermometer", "5"], ["Cotton Balls / Cotton-tipped Swabs", "Packs"], ["Cotton Balls / Cotton-tipped Swabs (Packs)", "Packs"], ["Two-point Discriminator", "4"], ["Monofilament Test Kit", "2"],
  ["Face Masks", "Packs"], ["Face Masks (Packs)", "Packs"], ["Disposable Gloves", "Packs"], ["Disposable Gloves (Packs)", "Packs"], ["Hand Sanitizer Dispensers", "5"], ["Sputum Containers", "Packs"], ["Sputum Containers (Packs)", "Packs"], ["Sterilizing Unit", "1"], ["Autoclave", "1"], ["Antiseptic Solution", "Packs"], ["Antiseptic Solution (Packs)", "Packs"], ["Washing Machine", "1"], ["Drying Machine", "1"], ["Sharps Disposal Bins", "5"], ["Biohazard Waste Bins", "5"],
  ["Alarm", "Placed in strategic locations"], ["Fire Extinguisher", "Placed in strategic locations"], ["Fire Blanket", "Placed in strategic locations"], ["Intercom", "Placed in strategic locations"], ["Fire Assembly Point Signage", "Placed in strategic locations"], ["Sand Bucket", "Placed in strategic locations"], ["Clearly Marked Direction to Muster Point", "All facility"], ["First Aid Kits", "Placed in strategic locations"], ["Emergency Exit Lights", "All facility"]
]);

export const OCCUPATIONAL_THERAPY_CLINICAL_QTY_MAP = buildMap([
  ["Relaxation Chair", "5"], ["Floor Sitter", "5"], ["Stand-in Frame", "5"], ["Stand-in Table", "5"], ["Transfer Equipment", "3"], ["Wedges (triangular, high and low, split)", "3 each"], ["Pillows", "10"], ["Foam Rolls (cylindrical, half-cylindrical)", "3 each"], ["Convalescent Recliners", "5"],
  ["Steadiness Tester (Hole Type)", "5"], ["Pencil Maze Test Board", "5"], ["Tremor Quantifier", "5"], ["Hand Dynamometer", "5"], ["Strength Evaluation System", "5"], ["Goniometer", "5"], ["Finger Dexterity Test Board", "5"], ["Key Hole Test Board", "5"], ["Counting and Colour Sorting Beads Set", "10"], ["Tape Measure", "5"], ["Sensory Pins, Tuning Fork, Reflex Hammer", "1 set each"], ["Sphygmomanometer", "5"], ["Peak Flow Meters", "3"], ["Stop Watch/Alarm Clock/Metronome", "3 each"], ["Pain Rating Scale", "5"], ["Weighing Scale", "3"], ["Cognitive Assessment Tools (e.g. MoCA, MMSE)", "3 sets"], ["Sensory Processing Assessment Equipment", "3 sets"], ["Skin Fold Calipers", "3"], ["Pen Light", "3"],
  ["Treatment Tables/Plinths", "5"], ["Tilt Tables", "5"], ["Standing Frames", "5"], ["Mat Platforms", "5"], ["Parallel Bars/Stairs", "2 each"], ["Stools, Carts, Screens and Mirrors", "5 each"], ["Work Hardening Equipment", "5"], ["Trays and Accessories", "10"], ["Ramps", "2"], ["Wheel Chairs", "4"], ["Wax Warmer (Paraffin Bath)", "2"], ["Cryotherapy Machine", "2"], ["TheraBand/Resistance Bands (various grades)", "5 each"], ["Exercise Mats", "10"], ["Walkers and Mobility Aids", "3 each"], ["Giant Standing Mirrors", "3"],
  ["Alarm", "Strategic locations"], ["Fire Extinguishers", "Strategic locations"], ["Blankets", "Many"], ["Intercom", "-"], ["Fire Assembly Points", "Strategic locations"], ["Sand Buckets", "Strategic locations"], ["Clearly Marked Direction to Muster Points", "Strategic locations"], ["First Aid Box", "2"],
  ["Face Masks", "3 packs (at any point in time)"], ["Disposable Gloves", "3 packs (at any point in time)"], ["Hand Sanitizers", "6"], ["Antiseptic Solutions (Eusol, Savlon, Hibitane)", "1 carton"], ["Sterilizing Unit", "1"], ["Autoclave", "1"], ["Washing Machine", "1"], ["Drying Machine", "1"],
  ["Towels", "12 (at any given time)"], ["Mackintosh", "12 (at any given time)"], ["Bedsheets", "12 sets"], ["Thermoplastic Splinting Material (45×61 sheets)", "5 sets (on request)"], ["Velcro, Cotton Tape, Rivets, D-rings (splinting)", "1 set (on request)"], ["Lint, Felt, Foam Padding", "3 packs (at any given time)"], ["Crepe Bandage and Gauze", "3 packs (at any given time)"], ["Topical Agents (analgesic, emollient creams)", "3 packs (at any given time)"],
  ["Paediatric Treatment Tables", "5"], ["Vestibular Swing System", "2"], ["Trampoline (Paediatric)", "2"], ["Pacer Gait Trainer", "2"], ["Standers and Corner Seats", "5"], ["Paediatric Treadmill", "1"], ["Therapy Ball Pool", "1"], ["Pea Ball and Bolster", "5"], ["Prone Liner", "5"], ["Handy Vibrator", "2"], ["Exercise Wall Mirror", "5"], ["Therapy Mats (Paediatric)", "10"], ["Precision/Dexterity Training Cones", "12"], ["Adapted Eating and Drinking Aids", "2 sets"], ["Everyday Objects for ADL Practice", "Several"], ["Television Set (for visual feedback)", "1"], ["Partial Body Weight Support System with Harness", "2"], ["Resistance Bands (Paediatric)", "3 each"], ["Building Blocks Set", "5"], ["Puzzles (various levels)", "10"],
  ["Reacher", "5"], ["Dressing Aids", "5"], ["Home Accessories and Helpers", "5"], ["Mobility Aids and Leisure Activity Items", "5"], ["Scissors, Book Holder and Writing Aids", "5"], ["Door Latch Frame Set", "5"], ["Kitchen Frame Set/Simulated Kitchen Equipment", "5"], ["Dressing Frame Set", "5"], ["Eating Aids with Utensil Sets", "5"], ["ADL Kit Sets", "5"], ["ADL Board", "5"], ["Transfer Boards", "4"], ["Slide Sheets", "4"], ["Upper Limb Work Station", "2"], ["Arm Activity Kit (CIMT, Bimanual)", "2"], ["Upper Limb Support", "4"], ["Resistive Exercise Putty (dough)", "3"], ["Rollators", "3"], ["Balance Board/Cushion", "4"],
  ["Splinting Kit (static and dynamic)", "5 sets"], ["Thermoplastic Splinting Materials", "5 sets"], ["Gait Belts", "4"], ["Hand Exerciser", "5"], ["Orthoses Kit (upper and lower limb)", "3 sets"], ["Upper Limb Work Station", "2"], ["Stabilization/Mobilization Belts", "4"], ["Hot and Cold Packs", "6"], ["Foam Wedges (triangular, high and low, split)", "3 each"], ["Wrist/Elbow/Shoulder Supports and Slings", "5 each"], ["Sanding Unit (reciprocal, semi-circular, vertical, overhead)", "3"], ["Flexion/Extension/Pronation/Supination Apparatus", "3"], ["Multi-Purpose Wheel", "3"], ["Range of Motion Arc", "3"], ["Cervical/Thoracic/Pelvic Braces", "3 each"],
  ["Sewing Machine", "3"], ["Metal Work Equipment", "5"], ["Wood Work Equipment", "5"], ["Art and Craft Supplies (paints, clay, canvas)", "Assorted"], ["Music Therapy Equipment (instruments, speaker)", "1 set"], ["Leisure and Recreational Activity Items", "Several"], ["Cognitive Remediation Therapy Materials", "3 sets"], ["Social Skills Activity Cards and Boards", "5"], ["Video Recording Devices", "2"], ["Relaxation Chair", "5"], ["Target Game", "5"], ["Balance Board/Cushion", "3"], ["Resistance Bands (various grades)", "3 each"], ["Utensils for Activities of Daily Living", "Make available"],
  ["Adapted Eating and Drinking Aids", "5 sets"], ["Assistive Products for Dressing", "5 sets"], ["Assistive Products for Grooming/Hygiene", "5 sets"], ["Assistive Products for Toileting/Bathing", "5 sets"], ["Reacher and Grab Aids", "5"], ["Ergonomic Chair/Adjustable Furniture", "4"], ["Standing Frames", "3"], ["Wheel Chairs", "3"], ["Cognitive Assessment Materials", "3 sets"], ["Dementia Activity Kits (reminiscence boxes, puzzles)", "3 sets"], ["Compression Products/Stockings", "5"], ["Bed Positioning and Safety Products", "5"],
  ["Portable ADL Kit", "5"], ["Portable Assessment Tools (goniometer, dynamometer)", "3 each"], ["Assistive Devices (canes, crutches, frames, rollators)", "2 each"], ["Wheelchair (manual)", "3"], ["Ramps (portable)", "2"], ["Splinting Kit (portable)", "3 sets"], ["Resistance Bands (various grades)", "4 each"], ["Home Modification Assessment Checklist", "Several"], ["Therapeutic Toys", "Several"], ["Vocational Activity Materials", "Make available"], ["Community Re-integration Activity Kits", "Make available"],
  ["Thermoplastic Splinting Materials (45×61 sheets)", "5 sets"], ["Orfit Cutter, Heat Gun, Heat Pan", "1 each"], ["Cotton Tape, Velcro, Rivets, D-rings, Canvas", "1 set"], ["Shoulder Supports and Slings", "5"], ["Elbow Supports", "5"], ["Wrist Supports, Cock-up Splints, Resting Splints", "5"], ["Cervical Collars", "5"], ["Clavicular/Thoracic/Pelvis Braces", "5"], ["Ankle, Foot and Heel Supports", "5 each"], ["Knee Supports", "5"], ["Back Supports", "5"], ["Scar Management and Gel Products", "5"], ["Ergonomic Products (adjusters for chairs, tables, toilets)", "5"], ["Compression Products and Stockings", "5"], ["Edema Management Products", "5"], ["Taping Materials", "10 rolls"], ["Communication/AAC Devices (augmentative)", "2"],
  ["Work Simulation Equipment (filing, sorting, packing tools)", "5"], ["Sewing Machine", "3"], ["Metal Work Equipment", "5"], ["Wood Work Equipment", "5"], ["Computer with Assistive Software (screen readers, voice control)", "2"], ["Ergonomic Workstation Setup Equipment", "3 sets"], ["Functional Capacity Evaluation (FCE) Tools", "1 set"], ["Sand and Water Table", "2"], ["Strength Training Equipment (sand bags, weights)", "Various sizes"],
  ["Adapted Eating and Drinking Aids", "Make available"], ["Assistive Products for Dressing", "Make available"], ["Assistive Products for Toileting", "Make available"], ["Reacher and Grab Aids", "5"], ["Hot and Cold Packs", "6"], ["Foam Wedges and Rolls", "3 each"], ["Balance Board/Cushion", "3"], ["Resistance Bands (light grade)", "5"], ["Leisure and Recreational Activity Items", "Make available"], ["Relaxation and Mindfulness Aids", "Make available"], ["Compression Products and Stockings", "5"], ["Positioning Products (pillows, bolsters)", "10"],
  ["Tactile and Visual Stimulators (feathers, peg boards)", "5 each"], ["Target Game", "5"], ["Basic Balance Beam", "5"], ["Balances, Dartboard and Ball Pool", "Various sizes"], ["Puzzles (various levels)", "20"], ["Multi-Activity Work Station", "3"], ["Mushroom Boards", "3"], ["Pinch Tree Board", "5"], ["Size Perception Square Board Set", "5"], ["Television Set", "2"], ["Foot Placement Ladder", "5"], ["Equilibrium Board", "5"], ["Building Blocks Set", "5"], ["Visual Cues and Illustration Materials Set", "5"], ["Play Dough", "10"], ["Cone Board", "10"],
  ["Equipment for Bathing", "5"], ["Equipment for Toileting", "5"], ["Equipment for Grooming", "5"], ["Bed (Simulated)", "2"], ["Plates and Bowls", "5"], ["Cups and Drinking Aids", "5"], ["Self-Feeders and Arm Supports", "5"], ["Overbed Tables", "2"], ["Dycem Products (Non-slip surfaces)", "3"], ["Dining Accessories", "5"], ["Plate Rack", "2"], ["Oven", "2"], ["Oven Mitts", "2 pairs"], ["Gas Cooker", "3"], ["Mixer", "1"], ["Span Board (Cutting Surfaces)", "5"], ["Blender", "2"]
]);

export const SPEECH_THERAPY_ACADEMIC_QTY_MAP = buildMap([
  ["Hospital Bed Space", "250 minimum"],
  ["Embalmed Bodies", "1 cadaver per set of 8 students"], ["Anatomage", "1"], ["Equipment Trolleys", "3"], ["Electric Embalming Machine", "1"], ["Bone Cutting Equipment - Electric Saw/Drill", "2"], ["Articulated and Unarticulated Skeletons", "5"], ["X-Ray Viewing Boxes", "3"], ["Air-Conditions for the Dissecting Rooms and Air Extractors", "4"], ["Models", "5"], ["Slide for Sections", "Many"], ["Slide Projectors", "3"], ["Toilet Facilities:", "Gender sensitive"], ["Changing Room", "2"], ["Shower Room etc.", "1"],
  ["Microtome", "2"], ["Rotary/Sledge Microtome Knives", "3"], ["Light Microscopes Microtome", "1 per 2 students"], ["Vacuum Pump Dissecting Microtome", "3"], ["Cryostat with Microtome", "3"], ["Teaching Microscope", "3"], ["Electron Microscope", "1 per 2 students"], ["Slides", "Many"],
  ["Centrifuge", "6"], ["Ultracentrifuge", "2"], ["Electronic Balances", "2"], ["Heating Block", "8"], ["Vacuum Pumps", "2"], ["Spectrophotometer", "1 per 20 students"], ["PH. Metres", "1 per 20 students"], ["Thermostatic Water Bath", "1"], ["Bunner", "3 per bench"], ["Test tube varying size", "Many"], ["Distiller", "3"],
  ["Spirometer", "1 per 20 students"], ["Vitalograph", "1 per 20 students"], ["polygraph", "1"], ["Peak Flow Metre", "1 per 20 students"], ["Gas Metre", "2"], ["ECG Machine", "4"], ["Spectrophotometers", "1 per 20 students"], ["Physiograph Recorder Transducers", "1 per 20 students"], ["Oscilloscopes", "4"], ["Centrifuges", "6"], ["Blood Gas Callipers", "2"], ["Audiometer", "2"], ["Water Baths", "2"], ["Electronic Weighing Balance Scale", "2"], ["Flame Photometer", "4"], ["Microcentrifuge", "2"], ["Water Distiller", "5"], ["Bicycle Ergometer", "3"], ["Stethoscope/ Sphygmomanometre", "12"], ["Snelle's Chart", "5"],
  ["Digital Audio Recorder", "2"], ["Video Recorder /HD Camera", "2"], ["Laptop with Speech Analysis Software", "2"], ["Desktop Computer", "2"], ["High Quality Microphone", "2"], ["Noise Induced Headset", "3"], ["Portable Speaker", "2"], ["Stopwatch/Timer", "4"], ["Tablet for AAC and Testing Apps", "2"], ["Printer /Scanner for Test Protocols", "2"], ["Penlight", "5"], ["Tongue Depressors (Packs)", "10 boxes"], ["Oral Examination Mirror", "4"], ["Gloves (Boxes)", "10 boxes"], ["Reflex Hammer", "2"], ["IOPI Tongue Presssure Device", "1"], ["Respiratory Pressure Meter", "1"], ["Decibel Meter/SPL Meter", "2"], ["DDK Digital Counter", "1"], ["Acoustic Voice Analysis Software", "2"], ["Computerised Speech Lab (CSL)", "1"], ["Microphone Calibration System", "2"], ["Sound Level Meter", "2"], ["Electroglottograph(EGG)", "1"], ["Videostroboscopy", "1"], ["Laryngeal Endoscopy Tower", "1"], ["Nasometer", "1"], ["Nasopharyngoscope", "1"], ["Aerodynamic Airflow-Pressure System", "1"], ["Videofloroscopy Support Access", "1"], ["Tongue Pressure Device", "1"], ["Food Viscosity Testing Kit", "2"], ["VFSS/Modified Barium Swallow System", "1"], ["FEES Recording Software", "1"], ["Endoscope", "1"], ["Light Source", "1"], ["Monitor", "1"], ["Image Capture System", "1"], ["Speech Generating Device", "1"], ["Touch Screen Board", "1"], ["Symbol Communication Software", "1"], ["Pediatric Feeding Chair", "2"], ["Testure Testing Spoons", "2"], ["Syringes", "5"], ["Nipple Flow Testing Set", "2"], ["Bottle Teat Assessment Kit", "1"], ["Weighing Scale", "1"], ["Sensory Feeding Tools", "2"], ["Play Based Assessment Kits", "2"], ["Cognitive Communication Software", "2"], ["Language Sample Software", "1"], ["Standardizedtest Kit Cabinet", "1"], ["Seminar Projector", "1"], ["Video Teaching Archive System", "1"], ["Students Practical Kit", "1"],
  ["Face Masks (Packs)", "packs"], ["Disposable Gloves (Packs)", "Packs"], ["Sputum Containers (Packs)", "Packs"], ["Sterilizing Unit", "1"], ["Autoclave", "1"], ["Antiseptic Solution (Packs)", "packs"], ["Drying Machine", "1"],
  ["Standard Articulation Test Kits", "2"], ["Phonological Process Test Kit", "2"], ["Speech Analysis Software Workstation", "2"], ["Picture Naming Cards (Sets)", "5 sets"], ["Minimal Pair Cards (Sets)", "5 sets"], ["Tongue Depressors (Boxes)", "5 boxes"], ["Flashcards (Sets)", "10 sets"], ["Tactile Cue Tools", "5"], ["PROMPT Cueing Kits", "3"], ["Toys for Speech Elicitation (Sets)", "10 sets"],
  ["Aphasia Batteries (WAB/BDAE Type)", "3"], ["Language Test Batteries ( Adult And Pediatric)", "4"], ["Bedside Screening Kits", "5"], ["Literacy/Phonological Awareness Kits", "3"], ["Reading Comprehension Tools", "3"], ["Writing Task Boards", "4"], ["Story Sequencing Cards (Sets)", "10 sets"], ["Tablets/Laptops for Language Apps", "5"], ["Naming Therapy Software", "2"], ["Workbooks", "20"], ["Category Cards (Sets)", "10 sets"], ["Sentence Strips (Packs)", "10 packs"], ["Whiteboards", "4"],
  ["SSI-Type Fluency Tools", "1"], ["Stopwatch Timer", "4"], ["Audio-Video Recorder", "2"], ["Speech Rate Counter Apps/Devices", "2"], ["Delayed Auditory Feedback Devices", "2"], ["Breathing Trainer", "2"], ["Fluency Shaping Manuals", "4"], ["Counseling Materials (Sets)", "10 sets"],
  ["Laryngeal Mirror Sets", "3"], ["Acoustic Voice Analysis Software", "2"], ["Microphones (High Quality)", "3"], ["SPL Meter", "2"], ["Nasometer", "1"], ["Pitch Analyser", "2"], ["Voice Range Profile Software", "2"], ["FEES System Access", "1"], ["Flexible Laryngoscope Access", "1"], ["Stroboscopy Access", "1"], ["Resonance Tubes/Straw Phonation Kits", "10"], ["Breathing Trainer", "4"], ["Biofeedback Monitor", "2"],
  ["Dysphagia Bedside Kits", "4"], ["Purse Oximeters", "3"], ["Cervical Auscultation Stethoscope", "2"], ["Food Texture Kits", "3"], ["Thickener Stock (Tins)", "5 tins"], ["Syringes/Spoons/Cups", "20 each"], ["Oral Motor Exam Kits", "5"], ["FEES Access", "1"], ["VFSS Devices", "3"], ["EMST Devices", "3"], ["NMES Swallowing Devices", "2"], ["Adaptive Bottles", "5"], ["Specialty Nipples", "10"], ["High Chairs", "2"], ["Feeding Spoons", "20"],
  ["Cognitive-Linguistic Batteries", "2"], ["Memory Screening Tools", "3"], ["Executive Function Task Kits", "2"], ["Attention Testing Software", "2"], ["Problem Solving Cards (Sets)", "10 sets"], ["Sequency Boards", "5"], ["Memory Books", "10"], ["Orientation Boards", "3"], ["Tablet Cognitive Apps", "3"],
  ["Pragmatic Profile Tools", "3"], ["Autism Communication Screeners", "2"], ["Social Story Kits", "10"], ["Emotion Cards (Sets)", "8 sets"], ["Video Modelling Software", "2"], ["Turn Taking Games", "10"], ["Board Games", "10"], ["Role-Play Kits", "5"], ["Group Therapy Chairs/Table (Set)", "1 set"],
  ["Communication Boards", "10"], ["Picture Exchange Sets", "10"], ["Symbols Cards", "15"], ["Alphabet Boards", "10"], ["Speech Generating Devices", "3"], ["Tablets with AAC Apps", "5"], ["Eye Gaze System", "3"],
  ["Myofunctional Mirrors", "5"], ["Lip Resistance Tools", "5"], ["Tongue Trainers", "5"], ["Straw Hierachy Kits", "10"], ["Chewy Tubes", "10"], ["Jaw Grading Bite Blocks", "5"], ["Nasal Breathing Strips", "20"],
  ["Reading Passages", "10"], ["Phonics Cards", "10"], ["Letter Tiles (Boxes)", "10 boxes"], ["Writing Boards", "5"], ["Dyslexia Screening Tools", "3"], ["Reading Software", "2"],
  ["Acoustics Analysis Software", "2"], ["Pitch Tracker Apps", "4"], ["Resonance Feedback Software", "2"], ["High Quality Microphones", "2"], ["Video Modelling Resources", "2"], ["Counselling Room Setup", "1"],
  ["Alarm", "Should be Placed in strategic locations"], ["Fire Extinguisher", "Should be Placed in strategic locations"], ["Blanket", "Should be Placed in strategic locations"], ["Intercom", "Should be Placed in strategic locations"], ["Fire Assembly Point", "Should be Placed in strategic locations"], ["Sand Bucket", "Should be Placed in strategic locations"]
]);

export const SPEECH_THERAPY_CLINICAL_QTY_MAP = buildMap([
  ["Digital Audio Recorder", "2"], ["Video Recorder /HD Camera", "2"], ["Laptop with Speech Analysis Software", "2"], ["Desktop Computer", "2"], ["High Quality Microphone", "2"], ["Noise Induced Headset", "3"], ["Portable Speaker", "2"], ["Stopwatch/Timer", "4"], ["Tablet for AAC and Testing Apps", "2"], ["Printer /Scanner for Test Protocols", "2"], ["Penlight", "5"], ["Tongue Depressors (Pack)", "10 boxes"], ["Oral Examination Mirror", "4"], ["Gloves (Pack)", "10 boxes"], ["Reflex Hammer", "2"], ["IOPI Tongue Pressure Device", "1"], ["Respiratory Pressure Meter", "1"], ["Decibel Meter/SPL Meter", "2"], ["DDK Digital Counter", "1"], ["Acoustic Voice Analysis Software", "2"], ["Computerised Speech Lab(CSL)", "1"], ["Microphone Calibration System", "2"], ["Sound Level Meter", "2"], ["Electroglottograph(EGG)", "1"], ["Videostroboscopy", "1"], ["Laryngeal Endoscopy Tower", "1"], ["Nasometer", "1"], ["Nasopharyngoscope", "1"], ["Aerodynamic Airflow-Pressure System", "1"], ["Videofloroscopy Support Access", "1"], ["Tongue Pressure Device", "1"], ["Food Viscosity Testing Kit", "2"], ["VFSS/Modified Barium Swallow System", "1"], ["FEES Recording Software", "1"], ["Endoscope", "1"], ["Light Source", "1"], ["Monitor", "1"], ["Image Capture System", "1"], ["Speech Generating Device", "1"], ["Touch Screen Board", "1"], ["Symbol Communication Software", "1"], ["Paediatric Feeding Chair", "2"], ["Texture Testing Spoons", "2"], ["Syringes", "5"], ["Nipple Flow Testing Set", "2"], ["Bottle Teat Assessment Kit", "1"], ["Weighing Scale", "1"], ["Sensory Feeding Tools", "2"], ["Play Based Assessment Kits", "2"], ["Cognitive Communication Software", "2"], ["Language Sample Software", "1"], ["Standardized Test Kit Cabinet", "1"], ["Seminar Projector", "1"], ["Video Teaching Archive System", "1"], ["Students Practical Kit", "1"],
  ["Alarm", "Should be Placed in strategic locations"], ["Fire Extinguisher", "Should be available in strategic locations"], ["Blanket", "Many"], ["Intercom", "-"], ["Fire Assembly Point", "Should be Placed in strategic locations"], ["Sand Bucket", "Should be Placed in strategic locations"], ["Clearly marked direction to muster point", "Should be Placed in strategic locations"],
  ["Face Masks (Pack)", "3 Packs (at any point in time)"], ["Disposable Gloves (Pack)", "3 Packs (at any point in time)"], ["Sputum Containers", "3"], ["Sterilizing Unit", "1"], ["Autoclave", "1"], ["Antiseptic Solution (Carton/Pack)", "1 carton"], ["Washing Machine", "1"], ["Drying Machine", "1"],
  ["Tongue Depressors (Pack)", "10"], ["Disposable Gloves (Pack)", "2packs"], ["Oral Swabs (Pack)", "10"], ["Disposable Spoons (Pack)", "15"], ["Disposable Cups (Pack)", "15"], ["Drinking Straws (Pack)", "2packs"], ["Feeding Syringes (Pack)", "20"], ["Food Thickener Sachets (Pack)", "10"], ["Bibs/ Napkins", "10"], ["Tissues (Pack)", "10"], ["Suction Catheters (dysphagia clinic)", "15"], ["A4 Paper (Pack)", "2packs"], ["Pencils", "10"], ["Masking Tape", "5"], ["Cardboard Sheets", "15"], ["Coloured Paper", "20"], ["Therapy Worksheet Printout", "25"],
  ["Aphasia Batteries (WAB/BDAE type)", "3"], ["Language Test Batteries (adult and paediatric)", "4"], ["Bedside Screening Kits", "5"], ["Literacy/Phonological Awareness Kits", "3"], ["Reading Comprehension Tools", "3"], ["Writing Task Boards", "4"], ["Story Sequencing Cards (Set)", "10 sets"], ["Tablets/Laptops for Language Apps", "5"], ["Naming Therapy Software", "2"], ["Workbooks", "20"], ["Category Cards (Set)", "10 sets"], ["Sentence Strips (Pack)", "10 packs"], ["Whiteboards", "4"],
  ["SSI-type Fluency Tools", "1"], ["Stopwatch Timer", "4"], ["Audio-Video Recorder", "2"], ["Speech Rate Counter Apps/Devices", "2"], ["Delayed Auditory Feedback Devices", "2"], ["Breathing Trainer", "2"], ["Fluency Shaping Manuals", "4"], ["Counseling Materials (Set)", "10 sets"],
  ["Laryngeal Mirror Sets", "3"], ["Acoustic Voice Analysis Software", "2"], ["Microphones (high quality)", "3"], ["SPL Meter", "2"], ["Nasometer", "1"], ["Pitch Analyser", "2"], ["Voice Range Profile Software", "2"], ["FEES System Access", "1"], ["Flexible Laryngoscope Access", "1"], ["Stroboscopy Access", "1"], ["Resonance Tubes/Straw Phonation Kits", "10"], ["Breathing Trainer", "4"], ["Biofeedback Monitor", "2"],
  ["Dysphagia Bedside Kits", "4"], ["Purse Oximeters", "3"], ["Cervical Auscultation Stethoscope", "2"], ["Food Texture Kits", "3"], ["Thickener Stock", "5 tins"], ["Syringes/Spoons/Cups", "20 each"], ["Oral Motor Exam Kits", "5"], ["FEES Access", "1"], ["VFSS Devices", "3"], ["EMST Devices", "3"], ["NMES Swallowing Devices", "2"], ["Adaptive Bottles", "5"], ["Specialty Nipples", "10"], ["High Chairs", "2"], ["Feeding Spoons", "20"],
  ["Cognitive-linguistic Batteries", "2"], ["Memory Screening Tools", "3"], ["Executive Function Task Kits", "2"], ["Attention Testing Software", "2"], ["Problem Solving Cards (Set)", "10 sets"], ["Sequency Boards", "5"], ["Memory Books", "10"], ["Orientation Boards", "3"], ["Tablet Cognitive Apps", "3"],
  ["Pragmatic Profile Tools", "3"], ["Autism Communication Screeners", "2"], ["Social Story Kits", "10"], ["Emotion Cards (Set)", "8 sets"], ["Video Modelling Software", "2"], ["Turn Taking Games", "10"], ["Board Games", "10"], ["Role-play Kits", "5"], ["Group Therapy Chairs/Table", "1 set"],
  ["Communication Boards", "10"], ["Picture Exchange Sets", "10"], ["Symbols Cards", "15"], ["Alphabet Boards", "10"], ["Speech Generating Devices", "3"], ["Tablets with AAC Apps", "5"], ["Eye Gaze System", "3"],
  ["Myofunctional Mirrors", "5"], ["Lip Resistance Tools", "5"], ["Tongue Trainers", "5"], ["Straw Hierarchy Kits", "10"], ["Chewy Tubes", "10"], ["Jaw Grading Bite Blocks", "5"], ["Nasal Breathing Strips", "20"],
  ["Reading Passages", "10"], ["Phonics Cards", "10"], ["Letter Tiles (Box)", "10 boxes"], ["Writing Boards", "5"], ["Dyslexia Screening Tools", "3"], ["Reading Software", "2"],
  ["Acoustics Analysis Software", "2"], ["Pitch Tracker Apps", "4"], ["Resonance Feedback Software", "2"], ["High Quality Microphones", "2"], ["Video Modelling Resources", "2"], ["Counselling Room Setup", "1"]
]);

export const PROSTHETICS_ORTHOTICS_ACADEMIC_QTY_MAP = buildMap([
  ["Goniometer", "4"], ["Protractor", "2"], ["Measuring tape", "3"], ["Shoe measuring tape", "3"], ["Ruler", "2"], ["Spreading caliper (small & large)", "2"], ["Vernier caliper (small & large)", "4"], ["Precision spring compass", "2"], ["Alignment fixture for prostheses", "4"], ["Alignment fixture for orthotic joints", "2"], ["Knee centre jig", "2"], ["Mounting frame with a laser", "2"], ["Gait mirror", "1"], ["Parallel bars", "1 set"], ["Pressure mat", "1"],
  ["Surfoam files (flat, half-round, round)", "3 sets"], ["Plaster knives", "4"], ["Plaster shears", "2"], ["Plaster mixing bowls", "4"], ["Spatulas", "4"], ["Cast stool", "2"], ["Sand bath", "1"], ["Bench vise", "4"], ["Floor vise", "4"], ["Mandrel", "2"], ["3D scanner", "1"]
]);

export const PROSTHETICS_ORTHOTICS_CLINICAL_QTY_MAP = buildMap([
  ["Goniometer", "4"], ["Protractor", "2"], ["Measuring tape", "3"], ["Shoe measuring tape", "3"], ["Ruler", "2"], ["Spreading caliper (small & large)", "2"], ["Vernier caliper (small & large)", "4"], ["Precision spring compass", "2"], ["Alignment fixture for prostheses", "4"], ["Alignment fixture for orthotic joints", "2"], ["Knee centre jig", "2"], ["Mounting frame with a laser", "2"], ["Gait mirror", "1"], ["Parallel bars (Set)", "1 set"], ["Parallel bars", "1 set"], ["Pressure mat", "1"],
  ["Surfoam files (flat, half-round, round) (Sets)", "3 sets"], ["Surfoam files (flat, half-round, round)", "3 sets"], ["Plaster knives", "4"], ["Plaster shears", "2"], ["Plaster mixing bowls", "4"], ["Spatulas", "4"], ["Cast stool", "2"], ["Sand bath", "1"], ["Bench vise", "4"], ["Bench Vise", "4"], ["Floor vise", "4"], ["Floor Vise", "4"], ["Mandrel", "2"], ["3D scanner", "1"],
  ["Allen key set (Set)", "4"], ["Allen key set", "4"], ["T-Handled hex wrench", "4"], ["T-Handled Hex wench", "4"], ["Wrench", "2"], ["Combination spanner set (Set)", "2"], ["Combination spanner set", "2"], ["Combination box and open-end wrench set", "2"], ["Torque wrench", "2"], ["Torque screwdriver", "2"], ["Screwdriver set (Set)", "4"], ["Screwdriver set", "4"], ["Set of pliers (Set)", "2"], ["Set of pliers", "2"], ["Wire cutter", "2"], ["Hammer set (Set)", "2"], ["Hammer set", "2"], ["Hammer set (ball-peen, claw, rubber mallet, cross-peen, dead-blow)", "2"], ["Hand cabinet file (round, half-round, flat)", "2"], ["Metal hacksaw frame", "2"], ["Hacksaw blade", "4"], ["Sheet metal shears", "2"], ["Rivet set (Set)", "2"], ["Rivet set", "2"], ["Hole punch set (Set)", "2"], ["Hole punch set", "2"], ["Slot punch", "2"], ["Deburring knife", "2"], ["Sharpening stone", "2"],
  ["Floor-mounted drilling machine", "1"], ["Tabletop drilling machine", "2"], ["Hand drills (manual & electric)", "2 each"], ["Hand drill (manual and electric)", "2 each"], ["Shoe patching machine", "2"], ["Shoe stretcher, locking", "2"], ["Silicon rolling mill", "1"], ["Dust extraction system", "2"], ["Compressor", "1"], ["Vacuum pump", "2"], ["Hot air oven", "1"], ["Plastic welding machine", "1"], ["Jig machine", "1"], ["3D printer / CNC", "1"],
  ["Workbench for lamination", "2"], ["Resin mixing station", "1"], ["Sealing iron", "2"], ["PVA measuring set (Set)", "2"], ["PVA measuring set", "2"], ["Vacuum lines & manifolds", "2"], ["PPE sets (Sets)", "6"], ["PPE sets", "6"],
  ["Torque tester", "1"], ["Load test jig", "1"], ["Digital weighing scale", "1"], ["First aid station", "1"], ["Fire extinguisher", "2"], ["Emergency eye wash", "1"],
  ["Tool cabinet/box", "2"], ["Storage container", "2"], ["Swivel chair", "2"], ["Workbench for assembly", "2"], ["Workbench with drawer unit", "3"],
  ["Bending brace (Sets)", "2 sets"], ["Bending brace", "2 sets"], ["Charger 100-240V AC 50-60Hz", "2"], ["Complete toolbox", "2"], ["Curved seaming pliers", "3"], ["Cutting knife", "2"], ["Double open-end spanner set (Set)", "2"], ["Double open-end spanner set", "2"], ["Drill bit set for metal (Set)", "2"], ["Drill bit set for metal", "2"], ["Drill bit set for wood (Set)", "1"], ["Drill bit set for wood", "1"], ["Half round leather knife", "2"], ["Set of hexagon bits (Set)", "2"], ["Set of hexagon bits", "2"], ["Knives", "2"], ["Last cutter", "2"], ["Pipe reamer", "2"], ["Pipe spanner set (Set)", "2"], ["Pipe spanner set", "2"], ["Precision saw", "2"], ["Revolving eyelet punch", "2"], ["Sanding drum set (Set)", "2"], ["Sanding drum set", "2"], ["Scissors set (pinking shears, wave cut scissors, curved scissors, plaster scissors) (Set)", "Not specified"], ["Scissors set (pinking shears, wave cut scissors, curved scissors, plaster scissors)", "Not specified"], ["Scriber", "2"], ["Sole cutter", "2 each"], ["Spring clamp", "10"], ["Stapler", "2"], ["Staple remover", "2"], ["Tack remover", "3"], ["Tap and die set, HSS (Set)", "2"], ["Tap and die set, HSS", "2"], ["Tracing wheel", "2"], ["Tweezers", "2"], ["Vice jaws", "2"], ["Vise jaws protector", "2"], ["Wire hand brush", "5"], ["Workbench for lamination resin work", "2"], ["Wench", "1"],
  ["Examination beds", "Not specified"], ["Towels", "Not specified"], ["Plinths", "Not specified"], ["Pillows", "Not specified"], ["Blankets", "Many"], ["Mats", "Not specified"], ["Mackintosh", "Not specified"], ["Ergonomically-designed chairs", "Not specified"], ["Stools", "Not specified"], ["White Clinical Coats", "Not specified"], ["Long overalls", "Not specified"], ["Sterilized Dressings (Packs)", "Not specified"], ["Sterilized Dressings", "Not specified"], ["Face Masks (Packs)", "Not specified"], ["Face Masks", "Not specified"], ["Disposable Gloves (Packs)", "Not specified"], ["Disposable Gloves", "Not specified"], ["Measuring devices & sensation", "Not specified"]
]);

export const getActiveMap = (type: string) => {
  switch (type) {
    case 'physiotherapy_clinical': return CLINICAL_QTY_MAP;
    case 'physiotherapy_academic': return ACADEMIC_QTY_MAP;
    case 'audiology_academic': return AUDIOLOGY_ACADEMIC_QTY_MAP;
    case 'audiology_clinical': return AUDIOLOGY_CLINICAL_QTY_MAP;
    case 'occupational_therapy_academic': return OCCUPATIONAL_THERAPY_ACADEMIC_QTY_MAP;
    case 'occupational_therapy_clinical': return OCCUPATIONAL_THERAPY_CLINICAL_QTY_MAP;
    case 'speech_therapy_academic': return SPEECH_THERAPY_ACADEMIC_QTY_MAP;
    case 'speech_therapy_clinical': return SPEECH_THERAPY_CLINICAL_QTY_MAP;
    case 'prosthetics_orthotics_academic': return PROSTHETICS_ORTHOTICS_ACADEMIC_QTY_MAP;
    case 'prosthetics_orthotics_clinical': return PROSTHETICS_ORTHOTICS_CLINICAL_QTY_MAP;
    default: return ACADEMIC_QTY_MAP;
  }
};